export const regions = [
  "AE",
  "AR",
  "AT",
  "AU",
  "BE",
  "BG",
  "BR",
  "CA",
  "CH",
  "CI",
  "CZ",
  "DE",
  "DK",
  "EE",
  "ES",
  "FI",
  "FR",
  "GB",
  "HK",
  "HR",
  "HU",
  "ID",
  "IE",
  "IN",
  "IT",
  "JP",
  "KE",
  "KR",
  "LT",
  "MX",
  "NL",
  "NO",
  "NZ",
  "PH",
  "PL",
  "PT",
  "RS",
  "RU",
  "SE",
  "SK",
  "TR",
  "US",
  "ZA",
];

export const watchProviders = [
  { watchProviderName: "Apple iTunes", watchProviderId: "2" },
  { watchProviderName: "Google Play Movies", watchProviderId: "3" },
  { watchProviderName: "Amazon Prime Video", watchProviderId: 9 },
  { watchProviderName: "Netflix", watchProviderId: 8 },
  { watchProviderName: "Hulu", watchProviderId: 15 },
  { watchProviderName: "Chili", watchProviderId: 40 },
  { watchProviderName: "Rakuten TV", watchProviderId: 35 },
  { watchProviderName: "HBO Max", watchProviderId: 384 },
  { watchProviderName: "Disney Plus", watchProviderId: 337 },
  { watchProviderName: "Crunchyroll", watchProviderId: 283 },
];
